### ISSUE TITLE
Feature: add missing contributing docs

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/docs.opensauced.pizza#11]
### Is your feature request related to a problem? Please describe.

Fast forwarding [docs](https://docs.opensauced.pizza) deployment we skipped at least one essential article like "how to add a new document in the docs endpoint".

### Describe the solution you'd like

Potentially have a contributor who's inexperienced with [docusaurus](https://docusaurus.io/docs) add this document portraying their experience and we improve upon it.

### Describe alternatives you've considered

Link people to [docusaurus](https://docusaurus.io/docs) and forcing them to become masters of all.

**Comment by bdougie** [comment]
We should add a note about branch naming and how not working from the forked main branch is preferred and why.

Something to add to this, per this conversation: https://github.com/open-sauced/open-sauced/pull/1137#issuecomment-905107988

**Comment by 0-vortex** [comment]
> We should add a note about branch naming and how not working from the forked main branch is preferred and why.
> 
> Something to add to this, per this conversation: [open-sauced/open-sauced#1137 (comment)](https://github.com/open-sauced/open-sauced/pull/1137#issuecomment-905107988)

Not so sure about this one, if the feature you are pushing requires workflows it's pretty much needed. Otherwise not sure our docs are a replacement for the git flow docs :D
