### ISSUE TITLE
bug: dead contributing link in readme

### ISSUE THREAD

**Issue by samuelsycamore** [open-sauced/docs.opensauced.pizza#13]
### Describe the bug

The **Contributing guide** link in the README is broken. 

Right now it links to https://github.com/open-sauced/docs.opensauced.pizza/blob/main/CONTRIBUTING.md which gives a 404.

I believe it is supposed to link to either 
- https://github.com/open-sauced/.github/blob/25dd3626084579bd562a23d9f3db0b907a38f6fc/CONTRIBUTING.md (as the rest of GitHub does)
or
- https://docs.opensauced.pizza/contributing/getting-started/ (as the main Open Sauced repo README does)

### Steps to reproduce

Click on the link called **Contributing guide** under **🤝 Contributing** in the README.

### Affected services

docs.opensauced.pizza

### Platforms

Desktop, Mobile, Tablet, TV, VR

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
very good catch, it should be `[Contributing guide](https://docs.opensauced.pizza/contributing/getting-started/)` - albeit this is a very small fix, I'll assign myself to the ticket so nobody can snatch it from you during hacktoberfest, but would totally appreciate you contributing this if you feel like it!

**Comment by samuelsycamore** [comment]
Cheers, I'm on it!

**Comment by 0-vortex** [comment]
> Cheers, I'm on it!

Don't forget to `take` it like the docs mention :D
