### ISSUE TITLE
Feature: add official URL to the repository details page

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/docs.opensauced.pizza#3]
### Is your feature request related to a problem? Please describe.

When clicking the repository display settings (top right cog icon as a repository admin), the URL field is empty.

### Describe the solution you'd like

Fill out the URL input with the default value `http://open-sauced.github.io/docs.opensauced.pizza` and let the CNAME do its course.

Think only @bdougie can do that?

### Describe alternatives you've considered

Ping maintainers team for more information

**Comment by 0-vortex** [comment]
Assigning @bdougie as the "settings" cog in the top right repository display is still not available to maintainers :/

**Comment by bdougie** [comment]
I believe this is now fixed. Can you confirm and close this @0-vortex ?

**Comment by 0-vortex** [comment]
> I believe this is now fixed. Can you confirm and close this @0-vortex ?

TYVM, now do it for every other repo 😹
