### ISSUE TITLE
Feature: add more opensauced.pizza branding

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/docs.opensauced.pizza#32]
### Type of feature

Style

### Current behavior

We only have one logo and no pizza

### Desired solution

Add more sauce to the footer, the header and, potentially, the navigation bars.

Announcement bar with a default message would be nice.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deadreyo** [comment]
Are the graphical images/resources available?

**Comment by 0-vortex** [comment]
> Are the graphical images/resources available?

They are but they are also not up-to-date, @bdougie can we update https://github.com/open-sauced/assets or do we link to the new [landing page](https://github.com/open-sauced/landing-page)?

**Comment by Deadreyo** [comment]
My updates:

![firefox_GXA6S9mT2j](https://user-images.githubusercontent.com/52013393/193284147-8f503f72-8c5a-4719-81c1-286265c59d88.png)
![firefox_Y4CyRZaKqU](https://user-images.githubusercontent.com/52013393/193284170-a1d01c04-fb0b-4098-adc0-369b41735098.png)

Thoughts? Shall I make a PR?

**Comment by bdougie** [comment]
Waiting on getting the assets from the designer but will circle back with a zip. I will also update the assets repo
