### ISSUE TITLE
Bug:  contribution guide page showing 404 error

### ISSUE THREAD

**Issue by Vibhaa5** [open-sauced/docs.opensauced.pizza#33]
### Describe the bug

contribution page is showing 404 error.
Link is broken

### Steps to reproduce

Visit any of the repos and click the "contributing guide" link

### Affected services

opensauced.pizza, admin.opensauced.pizza, docs.opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
thanks for reporting this, good catch!

**Comment by 0-vortex** [comment]
.take
