### ISSUE TITLE
Feature: Link to JS testing course for contributors

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#37]
### Type of feature

📝 Documentation

### Current behavior

Thinking we should add a link on this in the docs

https://testingjavascript.com/

### Suggested solution

Something like this

For more info on testing React and JavaScript, check out this course. 

https://testingjavascript.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by teachjenntech** [comment]
Haii! Can I take this?

**Comment by teachjenntech** [comment]
Added:

For more info on testing React and JavaScript, check out this course [Testing JavaScript](https://testingjavascript.com/)

**Comment by 0-vortex** [comment]
> Haii! Can I take this?

The issues section should do the trick: https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues 🍕
