### ISSUE TITLE
Feature: Add git visualizer to the docs

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#38]
### Type of feature

📝 Documentation

### Current behavior

It would be cool to link the git visualizer in the docs. 

### Suggested solution

https://git-school.github.io/visualizing-git/#upstream-changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Do you happen to know some action to comment this on PRs when they get left behind?
