### ISSUE TITLE
Feature: document more on "npm run push"

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#39]
### Type of feature

📝 Documentation

### Current behavior

Current docs mentioned it as an experiement. We need to encourage more contributors to use it. 

```
You can also experiment with conventional commits by doing:

npm run push
```

### Suggested solution

Expand on why it is important to the release process. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
I hope someone other than me will do this ticket :D 

🍕🍕🍕🍕🍕🍕🍕🍕🍕

**Comment by AhnafSulficar** [comment]
.take
