### ISSUE TITLE
feature: add and customize head metadata

### ISSUE THREAD

**Issue by huynhicode** [open-sauced/docs.opensauced.pizza#45]
### Type of feature

📝 Documentation

### Current behavior

Current documentation does not contain head metadata.

https://docusaurus.io/docs/markdown-features/head-metadata

### Suggested solution

Add and customize head metadata to all markdown files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by huynhicode** [comment]
I'd like to take on this issue.

**Comment by 0-vortex** [comment]
> I'd like to take on this issue.

I assigned you manually but you could use the dot take comment :D 

Will check the PR shortly! 

Thanks a lot! 🍕

**Comment by huynhicode** [comment]
@0-vortex Thanks for your patience. I created a [PR](https://github.com/open-sauced/docs.opensauced.pizza/pull/59) for this issue.
