### ISSUE TITLE
Feature: New favicon

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#47]
### Type of feature

🍕 Feature

### Current behavior

We have new brand assets and we will need to update the favicon to the below link. 

https://github.com/open-sauced/assets/blob/main/logos/slice-White-Orange.png

![image](https://user-images.githubusercontent.com/5713670/194166740-c43ce6da-b9e7-40b0-91b3-20e3129ec6a3.png)

### Suggested solution

The logo will need to be downloaded and renamed and replaced here 👉🏾[favicon.ico](https://github.com/open-sauced/docs.opensauced.pizza/blob/main/static/favicon.ico). You can use a [favicon generator](https://realfavicongenerator.net/) to create the multiple sizes

### Additional context

Hacktoberfest contributions welcomed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by skukhniy** [comment]
May I be assigned to this issue?

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by Chirag8023** [comment]
.take
