### ISSUE TITLE
feature: update the logo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#48]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

The logo font is inter - https://github.com/open-sauced/assets/blob/main/Logos%20/wordmark-Black%20Text.png

![image](https://user-images.githubusercontent.com/5713670/194164624-ecac7f1a-4289-441c-b629-f2682756d0fe.png)

### Suggested solution

Replace this
![Screen Shot 2022-10-05 at 2 28 09 PM](https://user-images.githubusercontent.com/5713670/194167396-05278ef9-c312-4669-8950-063e110506da.png)

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by toukirkhan** [comment]
Please assign this to me

**Comment by toukirkhan** [comment]
@bdougie please assign this to me

**Comment by 0-vortex** [comment]
> @bdougie please assign this to me

Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by mleisy** [comment]
.take
