### ISSUE TITLE
docs: Rename "Technical Guide" category to "app.opensauced.pizza"

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/docs.opensauced.pizza#50]
### Type of feature

📝 Documentation

### Current behavior

Since the docs.opensauced is supposed to be the official documentation for all open-sauce repos, having a category with a very general name like "Technical Guide" is very confusing, especially that it focuses mostly on just app.opensauce, without even referencing it.
![image](https://user-images.githubusercontent.com/52013393/194437258-d69e1c5e-b783-475c-b30d-ff04257b17e3.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by Deadreyo** [comment]
> Hi, I would like to work on this.

Yeah of course! Just assign it to yourself and get on it :D
