### ISSUE TITLE
Bug: Logo does not respect darkmode

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#56]
### Describe the bug

![Screen Shot 2022-10-18 at 2 56 04 PM](https://user-images.githubusercontent.com/5713670/196552527-ba237933-0742-42d7-90ab-52a2a8c8d50a.png)

### Steps to reproduce

To fix this, we needs to check for dark mode and swap out the image. You can either right click and download or click the download image button. 

https://github.com/open-sauced/assets/blob/main/logos/logo-on-dark.png

This is outline in the docs to do here: https://github.com/open-sauced/docs.opensauced.pizza/blob/main/docusaurus.config.js#L27

the line that should be updated to respect dark mode https://github.com/open-sauced/docs.opensauced.pizza/pull/55/files

### Affected services

docs.opensauced.pizza

### Additional context

https://github.com/open-sauced/docs.opensauced.pizza/blob/main/docusaurus.config.js#L27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
Extra context, may be best to use "srcDark" property. https://docusaurus.io/docs/api/themes/configuration#navbar-logo-srcDark

**Comment by mleisy** [comment]
.take

**Comment by EthenThinkful** [comment]
There is a problem as this logo-on-dark does not have a transparent background and interferes with the black color in dark mode.
