### ISSUE TITLE
Feature: document default community files for our existing repositories

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/docs.opensauced.pizza#6]
### Is your feature request related to a problem? Please describe.

Since getting [default community files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) over at [open-sauced/.github](https://github.com/open-sauced/.github) we are not required to duplicate some of the boilerplate when creating new repositories.

### Describe the solution you'd like

Simplify GitHub documentation for community files and give visual examples for how they are used within @open-sauced 

### Describe alternatives you've considered

Make everyone silently wonder why things are so cool and just 🤷 often.

**Comment by Deadreyo** [comment]
So to make sure I understand the issue, a sufficient solution would be to replace the content inside the documenation pages Code of Conduit & Triage Guide with a short description/summary, link to their full pages on open-sauced/github & some screenshots of them being used in action correctly?

**Comment by 0-vortex** [comment]
> So to make sure I understand the issue, a sufficient solution would be to replace the content inside the documenation pages Code of Conduit & Triage Guide with a short description/summary, link to their full pages on open-sauced/github & some screenshots of them being used in action correctly?

I would not say replace as there is no mention of our community files, all of the above would go in as extra content inside the triage guide IMHO
