### ISSUE TITLE
Fix: update config to include Algolia appId & update Docusaurus version to the latest (2.2.0)

### ISSUE THREAD

**Issue by huynhicode** [open-sauced/docs.opensauced.pizza#60]
The current Docusuarus version for this repo is [2.0.0-beta.9](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.9). Suggest updating to the latest version: [2.2.0](https://github.com/facebook/docusaurus/releases/tag/v2.2.0).

An update to the site configuration will need to be made to include the [Algolia appID](https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration) prior to updating the Docusaurus version.

![Screen Shot 2022-12-27 at 4 01 08 PM](https://user-images.githubusercontent.com/35910788/209738116-75ee2784-5156-4981-8ca5-c7c68a2c4a2a.png)

**Comment by vedant-z** [comment]
@huynhicode May I work on this?

**Comment by 0-vortex** [comment]
@huynhicode might have accidentally fixed this in [v1.18.1](829857e694b76725bb2df2d623aa0d3f7e2f1dd1) 😅

**Comment by huynhicode** [comment]
Thank you @0-vortex !
