### ISSUE TITLE
Feature: Match the favicon from hot.opensauced.pizza

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#65]
### Type of feature

🍕 Feature

### Current behavior

The favicon is not great and should match the one from hot.opensauced.pizza

### Suggested solution

The favicon can be found and downloaded from here. 

https://github.com/open-sauced/hot/tree/beta/public

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by rameshchandra8520** [comment]
.take

**Comment by rameshchandra8520** [comment]
Do I need to change only this Favicon?  @bdougie 
![image](https://user-images.githubusercontent.com/114871196/227427643-e31f4e30-f298-4f42-9e0f-83493621a2a8.png)

**Comment by diivi** [comment]
> Do I need to change only this Favicon?

Hi, favicons are the icons your browser renders next to the title for every webpage.

![image](https://user-images.githubusercontent.com/41837037/227435561-15c3b757-8b2a-49e5-a317-662152aff338.png)

To solve this issue, you have to replace the current [docs.opensauced.pizza](https://docs.opensauced.pizza/) (the one on the left) favicon with the [hot.opensauced.pizza](https://hot.opensauced.pizza/)  (the one on the right) favicon.

**Comment by Rishav1707** [comment]
Shall I work on this issue? @bdougie

**Comment by diivi** [comment]
This will help - https://github.com/open-sauced/assets

**Comment by bdougie** [comment]
I fixed the .take actions

https://github.com/open-sauced/open-sauced/commit/3a546dfb1cadfe98e8fb97986d9fdd0a67234d47

**Comment by Rishav1707** [comment]
Ok
