### ISSUE TITLE
Feature: Update Favicon to Pizza

### ISSUE THREAD

**Issue by bdougie** [open-sauced/docs.opensauced.pizza#80]
### Type of feature

🍕 Feature

### Current behavior
The favicon is not legible. 

<img width="129" alt="Screen Shot 2023-05-05 at 6 44 30 AM" src="https://user-images.githubusercontent.com/5713670/236474887-d7116330-92a5-4850-a502-4756a302e175.png">

### Suggested solution
To solve this issue, you have to replace the current [docs.opensauced.pizza](https://docs.opensauced.pizza/) (the one on the left) favicon with the [hot.opensauced.pizza](https://hot.opensauced.pizza/) (the one on the right) favicon.

![227435561-15c3b757-8b2a-49e5-a317-662152aff338](https://user-images.githubusercontent.com/5713670/236474561-b3c42e9e-6cb2-4dd2-9bc5-320e5cfdbfdb.png)

### Additional context

Previous issue #65 was meant to fix this and it didn't

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by MZHoffman** [comment]
I hope I did it as I should. really easy issue just replaced code in SVG that was responsible for favicon. not sure if the file favicon.ico is necessary

**Comment by MZHoffman** [comment]
Had to change PR as the commit did not have the right name https://github.com/open-sauced/docs.opensauced.pizza/pull/82
