### ISSUE TITLE
Feature: chrome extension add post to highlight

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/docs.opensauced.pizza#93]
### Type of feature

📝 Documentation

### Current behavior

We need to create documentation for the post to highlight features in the extension. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Things need to be added while doing this PR: 
![image](https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/aa10eabe-3c01-4921-956a-ab85bada1575)
Explaining the AI panel 

Show the highlight button: 
![image](https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/e7a745c8-204e-4a4d-b313-867ab99af0b2)

Explain the post to highlight: 
![image](https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/c3a1c606-647d-4277-bb61-5e531b788468)

Explain the errors generated and the solution to them based on the code; 

https://github.com/open-sauced/ai/blob/dde39f102352480ecea6c7d772a9acb8ed23bb56/src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts#L54-L90

Show a gif of a successful post.

**Comment by a0m0rajab** [comment]
Explain how the title is being scrapped from the issue/PR page.

**Comment by a0m0rajab** [comment]
Error gif example:
![error_gif](https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/f6968a71-c344-495f-8eed-f1de9aff7599)

**Comment by a0m0rajab** [comment]
Successful use of the post 
https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/32ba2180-8971-4246-847d-ca4753e614c1

Solving errors and using the AI configuration tab. 
https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/61355be7-a391-405c-91a3-dcd0b5c9dc42

Will need to convert this videos to Gif later.

**Comment by bdougie** [comment]
> Will need to convert this videos to Gif later.

You can use https://ezgif.com for that.

**Comment by a0m0rajab** [comment]
Thanks, I just added them as checkpoint (had to work on other things) 

Gif Successful: 
![ezgif-3-4a07354222](https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/723ac624-e996-45f8-acdf-0d3ff08af90b)

Change configuration: 
![ezgif-3-43e056fc1f](https://github.com/open-sauced/docs.opensauced.pizza/assets/18273833/fa19fa8e-e652-461c-8df4-6e959c9b9943)
